[package]
name = "seaweed"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
thiserror = "2.0.14"

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "pkl"
path = "src/main.rs"
